import { createFontPreset } from "./create-font-preset";

export const FONT_PRESETS = [
  createFontPreset(
    "manrope-grotesk",
    "Manrope + Space Grotesk",
    "Current default.",
    "\"Manrope\", \"Avenir Next\", \"Segoe UI\", sans-serif",
    "\"Space Grotesk\", \"Manrope\", sans-serif",
  ),
  createFontPreset(
    "comet-browser",
    "Comet Browser",
    "Comet font first, then modern browser-safe fallbacks.",
    "\"Comet\", \"Inter\", \"Segoe UI\", \"Avenir Next\", sans-serif",
    "\"Comet\", \"Space Grotesk\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "system-modern",
    "System Modern",
    "Neutral system UI stack.",
    "\"Segoe UI\", \"Avenir Next\", \"Inter\", sans-serif",
    "\"Segoe UI\", \"Avenir Next\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "inter-clean",
    "Inter Clean",
    "Straightforward, highly legible sans.",
    "\"Inter\", \"Segoe UI\", sans-serif",
    "\"Inter\", \"Segoe UI\", sans-serif",
  ),
  createFontPreset(
    "poppins-rounded",
    "Poppins Rounded",
    "Geometric sans with soft feel.",
    "\"Poppins\", \"Inter\", sans-serif",
    "\"Poppins\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "plus-jakarta",
    "Plus Jakarta",
    "Modern UI sans with sharper heading rhythm.",
    "\"Plus Jakarta Sans\", \"Inter\", sans-serif",
    "\"Plus Jakarta Sans\", \"Space Grotesk\", sans-serif",
  ),
  createFontPreset(
    "figtree-neat",
    "Figtree Neat",
    "Balanced proportions for compact layouts.",
    "\"Figtree\", \"Inter\", sans-serif",
    "\"Figtree\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "dm-sans",
    "DM Sans",
    "Friendly sans for dense UI text.",
    "\"DM Sans\", \"Inter\", sans-serif",
    "\"DM Sans\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "ibm-plex",
    "IBM Plex",
    "Technical sans with subtle character.",
    "\"IBM Plex Sans\", \"Inter\", sans-serif",
    "\"IBM Plex Sans\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "rubik-ui",
    "Rubik UI",
    "Rounded-square sans for UI controls.",
    "\"Rubik\", \"Inter\", sans-serif",
    "\"Rubik\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "outfit-display",
    "Outfit Display",
    "Contemporary geometric display sans.",
    "\"Outfit\", \"Inter\", sans-serif",
    "\"Outfit\", \"Space Grotesk\", sans-serif",
  ),
  createFontPreset(
    "nunito-soft",
    "Nunito Soft",
    "Warm rounded sans for approachable UI.",
    "\"Nunito\", \"Inter\", sans-serif",
    "\"Nunito\", \"Inter\", sans-serif",
  ),
  createFontPreset(
    "source-sans",
    "Source Sans",
    "Neutral professional sans.",
    "\"Source Sans 3\", \"Segoe UI\", sans-serif",
    "\"Source Sans 3\", \"Segoe UI\", sans-serif",
  ),
  createFontPreset(
    "editorial",
    "Editorial",
    "Serif body with classic serif headings.",
    "\"Georgia\", \"Times New Roman\", serif",
    "\"Georgia\", \"Times New Roman\", serif",
  ),
  createFontPreset(
    "lora-editorial",
    "Lora Editorial",
    "Readable serif body with elegant headings.",
    "\"Lora\", \"Georgia\", serif",
    "\"Lora\", \"Georgia\", serif",
  ),
  createFontPreset(
    "playfair-classic",
    "Playfair Classic",
    "High-contrast serif for strong title presence.",
    "\"Merriweather\", \"Georgia\", serif",
    "\"Playfair Display\", \"Merriweather\", serif",
  ),
  createFontPreset(
    "mono-tech",
    "Mono Tech",
    "Monospace-heavy preset for technical style.",
    "\"JetBrains Mono\", \"Consolas\", monospace",
    "\"JetBrains Mono\", \"Consolas\", monospace",
  ),
];
